##' Extract individual plates from an excel file
##'
##' This function extracts individual plate data from an excel file
##' containing readouts of plates. The excel file can contain multiple
##' sheets and/or multiple plates per sheet. Each plate should have
##' its own row- and column-names, with row-names A, B, ..., and
##' column-names 1, 2, .... Each readout is assumed to be part of a
##' series, with a numeric identifier in the top-left corner of the
##' plate (same row as colunm-names and same column as row-names).
##' @param filename A character variable with the file name of the
##'     excel file.
##' @return A list of matrices of type character. The names of the
##'     list are the identifiers described above.
.collectPlates <- function (filename) {
    plates <- list()
    for (sheet in openxlsx::getSheetNames(filename)) {
        first <- 1
        last <- 0
        sheetdata <- openxlsx::read.xlsx(filename, sheet, colNames = FALSE)
        sheetmat <- as.matrix(sheetdata)
        while (last < nrow(sheetmat)) {
            while (first < nrow(sheetmat) &&
                   !grepl("[[:digit:]]+", sheetmat[first, 1]))
                first <- first + 1
            last <- first
            while (last < nrow(sheetmat) &&
                   !grepl("[[:digit:]]+", sheetmat[last+1, 1]))
                last <- last + 1
            plates[[sheetmat[first, 1]]] <-
                sheetmat[first:last, 1:ncol(sheetmat)]
            if (last == nrow(sheetmat))
                break
            first <- first + 1
        }
    }
    plates
}


##' Collect measurements from a list of plates
##'
##' This function extracts the measurements from plates stored in a
##' list of matrices of type character, as generated by
##' '.collectPlates'. Each matrix is assumed to be a plate, with row-
##' and column-names present. Row-names are assumed to be A, B, ...,
##' and column-names 1, 2, .... The measurements from each plate are
##' extracted, and combined in a single data.frame, with one column
##' per well. Only wells which have at least one data point are
##' included.
##'
##' The columns of the data.frame can be ordered by the row or column
##' of the plate. This can be convenient when replicates are placed in
##' columns or in rows.
##' @param plates A list of matrixes of type character, as generated
##'     by '.collectPlates'.
##' @param order.by A character vector, either "columns" or "rows" (or
##'     an abbreviation of those). Defaults to "columns". If
##'     "columns", the column order of the output data.frame is A1,
##'     A2, A3, .... If "rows", the column order of the output
##'     data.frame is A1, B1, C1, ....
##' @return A data.frame with the plate measurements. Each well with
##'     at least one measurement is represented by a column, each
##'     plate is represented by a row. Column names are the
##'     identifiers for the wells.
.collectMeasurements <- function (plates,
                                 order.by=c("columns", "rows")) {
    order.by <- match.arg(order.by)
    dt <- data.table::rbindlist(lapply(plates, function (plate) {
        data.table::rbindlist(lapply(seq(2, nrow(plate)), function (row) {
            columns <- which(!is.na(plate[row, seq(2, ncol(plate))]))
            data.table::rbindlist(lapply(columns, function (column) {
                list(row = plate[row, 1], column = column,
                     well = paste0(plate[row, 1], column),
                     value = as.numeric(plate[row, column+1]),
                     measurement = as.integer(plate[1, 1]))
            }))
        }))
    }))

    ## Column ordering as if replicates are in the same row
    dtc <- data.table::dcast(dt, measurement ~ well, value.var="value")

    if (order.by == "columns") {
        ## Column ordering as if replicates are in the same column
        wellNames <- colnames(dtc)[-1]
        data.table::setcolorder(dtc,
                                c(1, order(column = substring(wellNames, 2),
                                           row = substr(wellNames, 1, 1))+1) )
    }
    as.data.frame(dtc)
}

##' Write collected measurements to a new file
##'
##' This function writes the collected measurements, as generated by
##' '.collectMeasurements' to a new file. This can either be an excel
##' file or a csv file.
##' @param data A data.frame with the collected measurements, as
##'     generated by '.collectMeasurements'.
##' @param filename The name of the output file.
##' @param format The character variable specifying the output file
##'     format. Can be "excel" or "xlsx" to output an excel file; or
##'     "csv" to output a csv file.
##' @return Nothing is returned but as a side effect the file
##'     specified in 'filename' is (over)written.
.writeMeasurements <- function (data,
                               filename,
                               format = c("excel", "xlsx", "csv")) {
    format <- match.arg(format, several.ok=TRUE)
    if ("csv" %in% format)
        data.table::fwrite(data, filename)
    if (any(c("excel", "xlsx") %in% format))
        openxlsx::write.xlsx(data, filename)
}


##' Extract repeated plate measurements from an excel file and order measurements by well
##'
##' This function extracts individual plate data from an excel file
##' containing readouts of plates. The excel file can contain multiple
##' sheets and/or multiple plates per sheet. Each plate should have
##' its own row- and column-names, with row-names A, B, ..., and
##' column-names 1, 2, .... Each readout is assumed to be part of a
##' series, with a numeric identifier in the top-left corner of the
##' plate (same row as colunm-names and same column as row-names).
##'
##' The measurements from each plate are extracted, and combined in a
##' single data.frame, with one column per well. Only wells which have
##' at least one data point are included.
##'
##' The columns of the data.frame can be ordered by the row or column
##' of the plate. This can be convenient when replicates are placed in
##' columns or in rows.
##'
##' The collected measurements are returned as a data.frame and
##' written to a new file (either excel or csv).
##' @param infile A character variable with the file name of the excel
##'     file containing the plate readouts.
##' @param outfile An optional character variable with the file name
##'     of the output file. If present has to end with ".xlsx" (to
##'     output an excel file) or ".csv" (to output a csv file). If no
##'     output file name is given, an excel file is generated using
##'     the same name as the input file, but with '.reformat'
##'     appended.
##' @param order.by An optional character vector, either "columns" or
##'     "rows" (or an abbreviation of those). Defaults to
##'     "columns". If "columns", the column order of the output
##'     data.frame is A1, A2, A3, .... If "rows", the column order of
##'     the output data.frame is A1, B1, C1, ....
##' @return Silently returns a data.frame with the plate
##'     measurements. Each well with at least one measurement is
##'     represented by a column, each plate is represented by a
##'     row. Column names are the identifiers for the wells. The rows
##'     of the data.frame are ordered by the numeric identifier of the
##'     plates, and the columns (depending on the value of 'order.by')
##'     either rows or columns of the plate. As a side effect the file
##'     specified in 'outfile' is (over)written.
##' @export
reformat.plates <- function (infile, outfile=NULL,
                             order.by=c("columns", "rows")) {
    ## defaults to grouping columns together
    order.by <- match.arg(order.by)
    ## Input file has to be an excel file
    stopifnot(endsWith(infile, ".xlsx"))
    
    ## if no output filename given, deduce from input filename
    ## output file type will be excel
    if (is.null(outfile)) {
        outfile <- sub(".xlsx$", ".reformat.xlsx",
                       infile, ignore.case=TRUE)
        out.format <- "xlsx"
    } else if (endsWith(outfile, ".xlsx")) {
        out.format <- "xlsx"
    } else if (endsWith(outfile, ".csv")) {
        out.format <- "csv"
    } else {
        stop("Output file type can only be .xlsx or .csv")
    }
    
    plates <- .collectPlates(infile)
    measurements <- .collectMeasurements(plates, order.by)
    .writeMeasurements(measurements, outfile, out.format)

    invisible(measurements)
}
